// SymbolCatalog.swift - Which SF Symbol spelling works on which macOS
//
// Reads symbol-catalog.json (generated by scripts/symbols/generate-symbol-catalog.py):
// every current symbol in gallery order, the macOS version its name first shipped in,
// and the older names (aliases) that draw the same glyph. A name the catalog does not
// know is not rejected; `status` asks the system instead.

import AppKit

struct MacOSVersion: Comparable, Hashable, Sendable, CustomStringConvertible {
    let major: Int
    let minor: Int

    init(_ major: Int, _ minor: Int = 0) {
        self.major = major
        self.minor = minor
    }

    init?(_ text: String) {
        let parts = text.split(separator: ".", omittingEmptySubsequences: false)
        guard (1...2).contains(parts.count),
              let major = Int(parts[0]),
              let minor = parts.count == 2 ? Int(parts[1]) : 0,
              major >= 0, minor >= 0 else { return nil }
        self.init(major, minor)
    }

    static let running: MacOSVersion = {
        let version = ProcessInfo.processInfo.operatingSystemVersion
        return MacOSVersion(version.majorVersion, version.minorVersion)
    }()

    static func < (lhs: MacOSVersion, rhs: MacOSVersion) -> Bool {
        (lhs.major, lhs.minor) < (rhs.major, rhs.minor)
    }

    var description: String { "\(major).\(minor)" }
}

extension MacOSVersion: Decodable {
    init(from decoder: Decoder) throws {
        let text = try decoder.singleValueContainer().decode(String.self)
        guard let version = MacOSVersion(text) else {
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath,
                debugDescription: "not a macOS version: \(text)"
            ))
        }
        self = version
    }
}

struct SymbolCatalog: Sendable {
    struct Alias: Decodable, Sendable {
        let name: String
        /// Nil when Apple's records predate the name. Such an alias is recognised
        /// but never chosen as a render name.
        let macOS: MacOSVersion?
    }

    struct Entry: Decodable, Sendable {
        let name: String
        let macOS: MacOSVersion
        let aliases: [Alias]

        private enum CodingKeys: String, CodingKey { case name, macOS, aliases }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            name = try container.decode(String.self, forKey: .name)
            macOS = try container.decode(MacOSVersion.self, forKey: .macOS)
            aliases = try container.decodeIfPresent([Alias].self, forKey: .aliases) ?? []
        }
    }

    enum Status: Equatable, Sendable {
        /// Draw `renderName`, which may differ from the name asked about.
        case available(renderName: String)
        /// The catalog knows the symbol, but no spelling of it exists before `MacOSVersion`.
        case needsNewerMacOS(MacOSVersion)
        /// Neither the catalog nor the system knows the name.
        case unknown
    }

    enum LoadError: Error, Equatable {
        case unsupportedFormat(Int)
        case duplicateName(String)
    }

    static let supportedFormatVersion = 1

    /// The symbols the gallery shows, in gallery order.
    let symbols: [Entry]
    /// Symbols that still resolve but that the gallery no longer shows.
    let retired: [Entry]

    private let entryByName: [String: Entry]

    init(data: Data) throws {
        struct File: Decodable {
            let formatVersion: Int
            let symbols: [Entry]
            let retired: [Entry]?
        }
        let file = try JSONDecoder().decode(File.self, from: data)
        guard file.formatVersion == Self.supportedFormatVersion else {
            throw LoadError.unsupportedFormat(file.formatVersion)
        }
        symbols = file.symbols
        retired = file.retired ?? []

        var byName: [String: Entry] = [:]
        for entry in symbols + retired {
            for name in [entry.name] + entry.aliases.map(\.name) {
                guard byName.updateValue(entry, forKey: name) == nil else {
                    throw LoadError.duplicateName(name)
                }
            }
        }
        entryByName = byName
    }

    private init() {
        symbols = []
        retired = []
        entryByName = [:]
    }

    /// The catalog shipped in the bundle; empty, rather than a crash, if it is missing.
    static let bundled: SymbolCatalog = {
        guard let url = Bundle.main.url(forResource: "symbol-catalog", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let catalog = try? SymbolCatalog(data: data) else {
            return SymbolCatalog()
        }
        return catalog
    }()

    // MARK: - Lookup

    func currentName(for name: String) -> String? {
        entryByName[name]?.name
    }

    func aliases(of name: String) -> [String] {
        entryByName[name]?.aliases.map(\.name) ?? []
    }

    /// The spelling to hand to `Image(systemName:)`, `NSImage(systemSymbolName:)` or
    /// `ISSymbolName` on `os`: the name itself if it exists there, else the current
    /// name, else the newest alias that exists there. Nil for a name the catalog does
    /// not know, or whose symbol has no spelling on `os`.
    func renderName(for name: String, on os: MacOSVersion) -> String? {
        guard let entry = entryByName[name] else { return nil }
        if name == entry.name {
            if entry.macOS <= os { return name }
        } else if let alias = entry.aliases.first(where: { $0.name == name }),
                  let introduced = alias.macOS, introduced <= os {
            return name
        }
        if entry.macOS <= os { return entry.name }
        return entry.aliases
            .filter { $0.macOS.map { $0 <= os } ?? false }
            .max { $0.macOS! < $1.macOS! }?
            .name
    }

    /// `renderName`, or `name` unchanged when the catalog has no spelling for it. What
    /// every drawing site uses, so a name the catalog does not know still reaches the
    /// system as typed.
    func drawableName(for name: String, on os: MacOSVersion = .running) -> String {
        renderName(for: name, on: os) ?? name
    }

    /// Whether `name` can be drawn on `os`, and under which spelling. A name the catalog
    /// does not know is put to `systemResolves`, so a valid name that postdates the
    /// catalog, or that it deliberately leaves out, is never refused.
    func status(
        of name: String,
        on os: MacOSVersion,
        systemResolves: (String) -> Bool = { NSImage(systemSymbolName: $0, accessibilityDescription: nil) != nil }
    ) -> Status {
        guard let entry = entryByName[name] else {
            return systemResolves(name) ? .available(renderName: name) : .unknown
        }
        if let renderName = renderName(for: name, on: os) {
            return .available(renderName: renderName)
        }
        let earliest = ([entry.macOS] + entry.aliases.compactMap(\.macOS)).min()!
        return .needsNewerMacOS(earliest)
    }

    /// The gallery as it should appear on `os`: every symbol with a spelling there,
    /// under that spelling, in gallery order.
    func galleryNames(on os: MacOSVersion) -> [String] {
        symbols.compactMap { renderName(for: $0.name, on: os) }
    }

    /// `galleryNames(on:)` narrowed to symbols with a spelling, current or alias, that
    /// contains `query`, ignoring case. An empty query narrows nothing.
    func galleryNames(on os: MacOSVersion, matching query: String) -> [String] {
        let query = query.trimmingCharacters(in: .whitespaces)
        guard !query.isEmpty else { return galleryNames(on: os) }
        return symbols.compactMap { entry in
            guard let name = renderName(for: entry.name, on: os) else { return nil }
            let spellings = [entry.name] + entry.aliases.map(\.name)
            return spellings.contains { $0.localizedCaseInsensitiveContains(query) } ? name : nil
        }
    }

    /// The current name of every symbol with a spelling on `os`, in gallery order. The
    /// calibration data is keyed by these, so its keys are the same on every OS.
    func currentNames(on os: MacOSVersion) -> [String] {
        symbols.filter { renderName(for: $0.name, on: os) != nil }.map(\.name)
    }

    /// `entries` with each key the catalog knows under another spelling moved to the
    /// current name. A value already under the current name wins; among other
    /// spellings, the first in sorted order does.
    func rekeyedToCurrentNames<Value>(_ entries: [String: Value]) -> [String: Value] {
        var result: [String: Value] = [:]
        var renamed: [(key: String, current: String)] = []
        for (key, value) in entries {
            let current = currentName(for: key) ?? key
            if current == key {
                result[key] = value
            } else {
                renamed.append((key, current))
            }
        }
        for (key, current) in renamed.sorted(by: { $0.key < $1.key }) where result[current] == nil {
            result[current] = entries[key]
        }
        return result
    }

    /// The spelling the gallery on `os` shows for the symbol `name` belongs to, or
    /// `name` unchanged when the catalog does not know it.
    func galleryName(for name: String, on os: MacOSVersion) -> String {
        currentName(for: name).flatMap { renderName(for: $0, on: os) } ?? name
    }
}
